//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CatalogueScanner.Core.Functions.SendCatalogueDigestEmailTemplate; 
using System;


/// <summary>
///   A strongly-typed resource class, for looking up localized strings, etc.
/// </summary>
// This class was auto-generated by the StronglyTypedResourceBuilder
// class via a tool like ResGen or Visual Studio.
// To add or remove a member, edit your .ResX file then rerun ResGen
// with the /str option, or rebuild your VS project.
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
internal class EmailTemplates {
    
    private static global::System.Resources.ResourceManager resourceMan;
    
    private static global::System.Globalization.CultureInfo resourceCulture;
    
    [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
    internal EmailTemplates() {
    }
    
    /// <summary>
    ///   Returns the cached ResourceManager instance used by this class.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static global::System.Resources.ResourceManager ResourceManager {
        get {
            if (object.ReferenceEquals(resourceMan, null)) {
                global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CatalogueScanner.Core.Functions.SendCatalogueDigestEmail.EmailTemplates", typeof(EmailTemplates).Assembly);
                resourceMan = temp;
            }
            return resourceMan;
        }
    }
    
    /// <summary>
    ///   Overrides the current thread's CurrentUICulture property for all
    ///   resource lookups using this strongly typed resource class.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static global::System.Globalization.CultureInfo Culture {
        get {
            return resourceCulture;
        }
        set {
            resourceCulture = value;
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to &lt;!doctype html&gt;
    ///&lt;html&gt;
    ///&lt;head&gt;
    ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width&quot; /&gt;
    ///    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot; /&gt;
    ///    &lt;title&gt;&lt;/title&gt;
    ///    &lt;style&gt;
    ///        /* -------------------------------------
    ///            GLOBAL RESETS
    ///        ------------------------------------- */
    ///
    ///        /*All the styling goes here*/
    ///
    ///        img {
    ///            border: none;
    ///            -ms-interpolation-mode: bicubic;
    ///            max-width: 100%;
    ///        }
    ///
    ///        bo [rest of string was truncated]&quot;;.
    /// </summary>
    internal static string HtmlTemplate {
        get {
            return ResourceManager.GetString("HtmlTemplate", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to %SUMMARY%
    ///
    ///%ITEMSLIST%
    ///
    ///Powered by Catalogue Scanner (https://github.com/Choonster/catalogue-scanner)..
    /// </summary>
    internal static string PlainTextTemplate {
        get {
            return ResourceManager.GetString("PlainTextTemplate", resourceCulture);
        }
    }
}
