name: Build Catalogue Scanner
description: Sets up the required .NET SDKs and builds the Catalogue Scanner solution

inputs:
  solution-file:
    description: The path of the solution file to build. Defaults to building the current directory if not provided.
    required: false
    default: .

  configuration:
    description: The build configuration to use
    required: false
    default: Release

runs:
  using: composite
  steps:
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore --locked-mode ${{ inputs.solution-file }}
      shell: bash

    - name: Build
      run: dotnet build --no-restore --configuration ${{ inputs.configuration }} ${{ inputs.solution-file }}
      shell: bash
