// Originally generated by quicktype (https://quicktype.io/), then manually cleaned up

using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace CatalogueScanner.WebScraping.Dto.ColesOnline
{
    public partial class ColrsCatalogEntryList
    {
        public string? Type { get; set; }
        public Categories? Categories { get; set; }
        public IEnumerable<Facet> Facets { get; } = new List<Facet>();
        public IEnumerable<Product> Products { get; } = new List<Product>();
        public SearchInfo? SearchInfo { get; set; }
    }

    public partial class Categories
    {
        [JsonPropertyName("parentCatgroup_id_search")]
        public IDictionary<string, string> ParentCatgroupIdSearch { get; } = new Dictionary<string, string>();
    }

    public partial class Facet
    {
        public IEnumerable<FacetValue> Values { get; } = new List<FacetValue>();
        public string? Name { get; set; }
        public bool ShowEspot { get; set; }
    }

    public partial class FacetValue
    {
        public long Count { get; set; }
        public string? Label { get; set; }
        public string? Value { get; set; }
    }

    public partial class Product
    {
        public Price? Price { get; set; }
        public AttributesMap? AttributesMap { get; set; }
        public string? ShortDescription { get; set; }

        [JsonPropertyName("singleSKUCatalogEntryID")]
        public string? SingleSkuCatalogEntryId { get; set; }

        public string? Manufacturer { get; set; }
        public string? Name { get; set; }
        public string? PartNumber { get; set; }
        public string? SeoToken { get; set; }
        public string? Thumbnail { get; set; }

        [JsonPropertyName("uniqueID")]
        public string? UniqueId { get; set; }

        public string? PurchaseLimit { get; set; }
        public string? UnitPrice { get; set; }

        [JsonPropertyName("tickettype")]
        public TicketType TicketType { get; set; }

        [JsonPropertyName("promo_min_qty")]
        public string? PromoMinQty { get; set; }

        [JsonPropertyName("promo_reward")]
        public string? PromoReward { get; set; }

        [JsonPropertyName("promo_type")]
        public PromoType? PromoType { get; set; }

        [JsonPropertyName("promo_desc")]
        public string? PromoDesc { get; set; }

        [JsonPropertyName("promo_id")]
        public string? PromoId { get; set; }

        public bool? Available { get; set; }
        public string? Rating { get; set; }
        public long Reviews { get; set; }
    }

    public partial class AttributesMap
    {
        [JsonPropertyName("AVERAGESIZE")]
        public IEnumerable<string> AverageSize { get; } = new List<string>();

        [JsonPropertyName("DELIVERYRESTRICTIONS")]
        public IEnumerable<string> DeliveryRestrictions { get; } = new List<string>();

        [JsonPropertyName("ONLINESIZEDESCRIPTION")]
        public IEnumerable<string> OnlinesizeDescription { get; } = new List<string>();

        [JsonPropertyName("LIQUORAGERESTRICTIONFLAG")]
        public IEnumerable<string> LiquorAgeRestrictionFlag { get; } = new List<string>();

        [JsonPropertyName("PRIMARYAISLE")]
        public IEnumerable<string> PrimaryAisle { get; } = new List<string>();

        [JsonPropertyName("WEIGHTEDITEMINDICATOR")]
        public IEnumerable<string> WeightedItemIndicator { get; } = new List<string>();

        [JsonPropertyName("EXCLUDEFROMSUBSTITUTIONFLAG")]
        public IEnumerable<string> ExcludeFromSubstitutionFlag { get; } = new List<string>();

        [JsonPropertyName("TOBACCOAGERESTRICTIONFLAG")]
        public IEnumerable<string> TobaccoAgeRestrictionFlag { get; } = new List<string>();

        [JsonPropertyName("TYPE")]
        public IEnumerable<string> Type { get; } = new List<string>();

        [JsonPropertyName("DISPLAYREVIEWS")]
        public IEnumerable<string> Displayreviews { get; } = new List<string>();
    }

    public partial class Price
    {
        public double? ListPrice { get; set; }
        public double OfferPrice { get; set; }

        [JsonPropertyName("isNaN")]
        public bool IsNaN { get; set; }

        public long DollarValue { get; set; }
        public long CentValue { get; set; }
    }

    public partial class SearchInfo
    {
        public long PageSize { get; set; }
        public string? SearchTerm { get; set; }
        public string? CategoryId { get; set; }
        public long SearchType { get; set; }
        public string? Manufacturer { get; set; }
        public string? ProfileName { get; set; }
        public string? SearchSource { get; set; }
        public string? IntentSearchTerm { get; set; }
        public string? OriginalSearchTerm { get; set; }
        public string? MetaData { get; set; }
        public string? Currency { get; set; }
        public string? FilterTerm { get; set; }
        public string? FilterType { get; set; }
        public string? FilterFacet { get; set; }
        public string? MaxPrice { get; set; }
        public string? MinPrice { get; set; }
        public string? OrderBy { get; set; }
        public string? PhysicalStoreIds { get; set; }
        public string? AdvancedFacetList { get; set; }
        public string? PageView { get; set; }
        public bool PersonaliseSearch { get; set; }
        public bool PersonaliseSort { get; set; }
        public string? ResponseTemplate { get; set; }
        public long CurrentPage { get; set; }
        public long TotalCount { get; set; }
        public bool ShowAddAllResults { get; set; }
        public Params? Params { get; set; }
    }

    public partial class Params
    {
    }

    [JsonConverter(typeof(JsonStringEnumMemberConverter))]
    public enum PromoType {
        MultibuyMultiSku, 
        MultibuySingleSku 
    }

    [JsonConverter(typeof(JsonStringEnumMemberConverter))]
    public enum TicketType
    {
        [JsonPropertyName("M")] M,
        [JsonPropertyName("M_0")] MZero,
        [JsonPropertyName("M_1")] MOne,
        [JsonPropertyName("S_0")] SZero,
        [JsonPropertyName("S_1")] SOne,
        [JsonPropertyName("S10_0")] STenZero,
        [JsonPropertyName("S15_0")] SFifteenZero,
        [JsonPropertyName("S15_1")] SFifteenOne,
        [JsonPropertyName("S20_0")] STwentyZero,
        [JsonPropertyName("S25_0")] STwentyFiveZero,
        [JsonPropertyName("S30_0")] SThirtyZero,
        [JsonPropertyName("S40_0")] SFourtyZero,
        [JsonPropertyName("S50_0")] SFiftyZero,
        [JsonPropertyName("V")] V,
        [JsonPropertyName("V_0")] VZero,
        [JsonPropertyName("X_0")] XZero
    }
}
