name: 'Build Application'

on:
  push:
  pull_request:
  workflow_dispatch:

env:   
  CONFIGURATION: 'Release'
  SHA_SUFFIX: ${{ github.ref_type == 'branch' && format('-{0}', github.sha) || '' }}
  FUNCTIONS_APP_OUTPUT_PATH: './CatalogueScanner.DefaultHost/output'
  CONFIGURATION_UI_OUTPUT_PATH: './CatalogueScanner.ConfigurationUI/output'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build application
        uses: ./.github/actions/build-catalogue-scanner
        with:
          configuration: ${{ env.CONFIGURATION }}

      - name: Publish Functions App to folder
        run: dotnet publish --no-build --configuration ${{ env.CONFIGURATION }} --output ${{ env.FUNCTIONS_APP_OUTPUT_PATH }}
      
      - name: Publish Configuration UI to folder
        run: dotnet publish --no-build --configuration ${{ env.CONFIGURATION }} --output ${{ env.CONFIGURATION_UI_OUTPUT_PATH }}

      - name: List GH ref name
        run: echo '${{ github.ref_name }}'
     
      - name: Archive Functions App
        uses: actions/upload-artifact@v2
        with:
          name: ${{ format('CatalogueScanner-{0}{1}', github.ref_name, env.SHA_SUFFIX) }}
          path: ${{ env.FUNCTIONS_APP_OUTPUT_PATH }}

      - name: Archive Configuration UI App
        uses: actions/upload-artifact@v2
        with:
          name: ${{ format('CatalogueScanner.ConfigurationUI-{0}{1}', github.ref_name, env.SHA_SUFFIX) }}
          path: ${{ env.CONFIGURATION_UI_OUTPUT_PATH }}
