name: Build and deploy to Production environment

on:
  push:
    branches:
      - master

jobs:
  build:
    uses: 'Choonster/catalogue-scanner/.github/workflows/reusable/build-application.yml@net6-update'

  deploy-functions-app:
    uses: 'Choonster/catalogue-scanner/.github/workflows/reusable/deploy-functions-app.yml@net6-update'
    needs: build
    with:
      artifact-name: ${{ needs.build.outputs.functions-app-artifact-name }}
      output-path: ${{ needs.build.outputs.functions-app-output-path }}
      app-name: catalogue-scanner-linux
    secrets:
      azure-credentials: ${{ secrets.AZURE_CREDENTIALS }}

  deploy-configuration-ui:
    uses: 'Choonster/catalogue-scanner/.github/workflows/reusable/deploy-configuration-ui.yml@net6-update'
    needs: build
    with:
      artifact-name: ${{ needs.build.outputs.configuration-ui-artifact-name }}
      output-path: ${{ needs.build.outputs.configuration-ui-output-path }}
      app-name: catalogue-scanner-configuration-ui
    secrets:
      azure-credentials: ${{ secrets.AZURE_CREDENTIALS }}
