on:
  push:

name: Deploy Bicep file to Azure

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.ARM_DEPLOYMENT_TEST_CREDENTIALS }}

      - name: Deploy Bicep file
        uses: azure/bicep-deploy@v2
        with:
          type: deployment
          operation: create
          resource-group-name: ${{ secrets.ARM_DEPLOYMENT_TEST_RG }}
          template-file: arm/main.bicep
          parameters-file: arm/parameters/deployment-test.parameters.json

      - name: Delete Resources
        uses: azure/bicep-deploy@v2
        with:
          type: deployment
          operation: create
          resource-group-name: ${{ secrets.ARM_DEPLOYMENT_TEST_RG }}
          template-file: arm/empty.bicep
          action-on-unmanage-resources: delete
          failOnStdErr: false
