name: Deploy Catalogue Scanner to Azure Functions

permissions:
  id-token: write

on:
  workflow_call:
    inputs:
      environment:
        description: Name of the GitHub Environment to deploy to
        required: true
        type: string

      artifact-name:
        description: Name of the Build Artifact to deploy
        required: true
        type: string

      output-path:
        description: Path of the build output in the Build Artifact
        required: true
        type: string

      app-name:
        description: Name of the Functions App to deploy to
        required: true
        type: string

      slot-name:
        description: Slot to deploy to
        required: false
        type: string

    secrets:
      azure-client-id:
        description: Azure application (client) ID to deploy with
        required: true

      azure-tenant-id:
        description: Azure directory (tenant) ID to deploy to
        required: true

      azure-subscription-id:
        description: Azure subscription ID to deploy to
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:
      - name: Download Artifact
        uses: Choonster/download-tartifact@2d57c52b41c93c32cf6ff20b65b19508974cd161
        with:
          name: ${{ inputs.artifact-name }}

      - name: Azure Login
        uses: Azure/login@v2
        with:
          client-id: ${{ secrets.azure-client-id }}
          tenant-id: ${{ secrets.azure-tenant-id }}
          subscription-id: ${{ secrets.azure-subscription-id }}

      - name: Publish to Azure
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ inputs.app-name }}
          slot-name: ${{ inputs.slot-name }}
          package: ${{ inputs.output-path }}
