name: 'Deploy Catalogue Scanner Configuration UI to Azure App Service'

on:
  workflow_call:
    inputs:
      artifact-name:
       description: Name of the Build Artifact to deploy
       required: true
       type: string
      
      output-path:
        description: Path of the build output in the Build Artifact
        required: true
        type: string
       
      app-name:
        description: Name of the Azure App Service to deploy to
        required: true
        type: string

      slot-name:
        description: Slot to deploy to
        required: false
        type: string

    secrets:
      azure-credentials:
        description: Azure credentials to deploy with
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Download Artifact
        uses: alehechka/download-tartifact@v1
        with:
          name: ${{ inputs.artifact-name }}

      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.azure-credentials }}
        
      - name: Publish to Azure
        uses: Azure/webapps-deploy@v2
        with:
          app-name: '${{ inputs.app-name }}'
          slot-name: '${{ inputs.slot-name }}'
          package: '${{ inputs.output-path }}'
