on: [push]
name: Deploy Bicep File to Azure
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.ARM_DEPLOYMENT_TEST_CREDENTIALS }}

      # Deploy Bicep file
    - name: deploy
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.ARM_DEPLOYMENT_TEST_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.ARM_DEPLOYMENT_TEST_RG }}
        template: arm/main.bicep
        parameters: arm/parameters/deployment-test.parameters.json
        failOnStdErr: false
